# Generated by Django 4.1.7 on 2023-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_picture',
            field=models.ImageField(default=None, null=True, upload_to='blog_pictures'),
        ),
    ]
